// Generated by scripts/build-legal-content.mjs from the archived WordPress export.
// Edit the copy here directly; the generator is kept only for re-running the migration.
import type { LegalDocument } from "@/components/content/document";

export const termsAndConditions: LegalDocument = {
  title: "Terms and Conditions",
  summary: "The terms that govern your use of the SFLuv website and services.",
  blocks: [
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Terms of Use"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "Welcome to the SFLuv website (the “Website”), operated by us. We are a 501(c)(3) nonprofit that supports local merchants and small businesses in underserved neighborhoods through our community project management platform and SFLuv stable tokens."
      ]
    },
    {
      type: "paragraph",
      children: [
        "By accessing the Website, you agree to be bound by these Terms of Use and all applicable federal, state, and local laws and regulations."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Privacy Policy"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "We value and respect your privacy. If you use the Website, you agree that your activities are covered by our Privacy Policy. ",
        {
          type: "link",
          href: "/privacy-policy",
          children: [
            "https://sfluv.org/privacy-policy"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Use of Publications, Trademarks, and Logos"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "We provide information and resources about SFLuv, local economies, blockchain technology and other related issues, including articles, press releases, photographs, merchant and community member stories and case studies, reports, newsletters, video broadcasts, e-newsletters, financial updates, and interviews with personnel, corporate and community partners, clients, and volunteers (collectively, “Publications”). Unless otherwise expressly stated, all content provided on the Website is intellectual property that belongs to us."
      ]
    },
    {
      type: "paragraph",
      children: [
        "You are permitted to download information from the Website for your own personal informational use. You may also copy, distribute, adapt, and transmit content from this Website solely for not-for-profit or educational purposes, provided that the use contains the following attribution: “Reproduced with permission of SFLuv”. You may not suggest any other relationship, endorsement or affiliation with us unless you obtain express written permission."
      ]
    },
    {
      type: "paragraph",
      children: [
        "For any other use, you must obtain express written permission from us."
      ]
    },
    {
      type: "paragraph",
      children: [
        "You may not use or duplicate any SFLuv logos or trademarks without express written permission from us."
      ]
    },
    {
      type: "paragraph",
      children: [
        "To request permission for use of copyrighted material, trademarks, or logos, send an email to ",
        {
          type: "link",
          href: "mailto:admin@sfluv.org",
          children: [
            "admin@sfluv.org"
          ]
        },
        "."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Age Restrictions and Parental Consent"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "You must be at least 16 years old to make donations, payments, purchases, or provide personal information through this website. If you are between the ages of 13-16, you may only do so with the supervision and consent of a parent or legal guardian. Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13."
      ]
    },
    {
      type: "paragraph",
      children: [
        "By proceeding with any donation, payment, purchase, or providing personal information, you confirm that you meet the age requirement or have obtained the necessary parental or guardian consent. We reserve the right to void any transactions, delete personal information, or restrict access if we become aware that these requirements have not been met."
      ]
    },
    {
      type: "paragraph",
      children: [
        "Parents or legal guardians are responsible for supervising any donations, payments, purchases, or personal information provided by minors under their care."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Links to Other Websites"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "Links on the Website that lead to outside services and resources are provided for convenience only. We do not control the accuracy or availability of those outside services and resources. SFLuv does not endorse those organizations or the information provided by other organizations. Any concerns regarding any such service or resource, or any link, should be directed to the particular service or resource."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Third Party Content"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "We respect copyright and trademark laws. Third-party material may appear on our site, and those creators retain all rights to their works, except where noted."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "No Guarantees"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "Though we strive to keep the information available on the Website current and accurate, errors can [and do] occur. We provide the information on the Website with no representations or guarantees of accuracy, completeness, or timeliness. SFLuv will not be liable to you or any other person for any damages that result from the use or inability to use the Website, or as a result of any content, information, services, or resources made available through the Website."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Indemnification"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "You agree to indemnify and hold harmless each of us, our affiliates, officers, directors, employees and volunteers from any claim or demand, including reasonable attorneys’ fees, made by any third party due to, arising out of, or related to your use of this Website, the violation of these Terms of Use by you, or the infringement by you of any intellectual property or other right of any person or entity."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "About These Terms – General Provisions"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "If we do not immediately take action to address a violation of these Terms of Use, we are not waiving our rights to take action in the future. If any particular provision of these Terms of Use is found to be unenforceable, that provision will be severable and will not affect any of the other provisions. This Website is owned and operated by us from our offices in California. Your use of the Website, and any related legal action, will be governed by the laws of the State of California, without regard to conflict of laws principles. The sole jurisdiction for any litigation arising out of your use of or inquiries to the Website will be an appropriate federal or state court located in San Francisco, California."
      ]
    },
    {
      type: "paragraph",
      children: [
        {
          type: "strong",
          children: [
            "Changes to the Terms of Use"
          ]
        }
      ]
    },
    {
      type: "paragraph",
      children: [
        "We reserve the right to make changes to any information or services on the Website, including these Terms of Use, without notice to you. The most current Terms of Use will be posted here on the Website and will be effective upon posting. The Effective Date will be posted with the most current Terms of Use. Be sure to return to this page periodically to ensure familiarity with the most current version of these Terms of Use."
      ]
    },
    {
      type: "paragraph",
      children: [
        "Effective Date: August 6, 2024"
      ]
    }
  ]
};
